##Spring Configuration
server:
  port: 8081
spring:
  r2dbc:
    host: localhost
    port: 5432
    database: request_db
    username: crediya_user
    password: crediya_password
    sql:
      init:
        mode: always
  application:
    name: requests-service
  devtools:
    add-properties: false
  profiles:
    include:
