server:
  port: 8081
spring:
  r2dbc:
    host: "localhost"
    port: 5434
    database: "request_db"
    username: "crediya_user"
    password: "crediya_password"
    sql:
      init:
        mode: "always"
  application:
    name: "requests-service"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    org.springframework.web: DEBUG
    reactor.netty: DEBUG